<?php

namespace Database\Seeders;

use App\Models\Award;
use App\Models\DocumentCategory;
use App\Models\NewsArticle;
use App\Models\NewsCategory;
use App\Models\Official;
use App\Models\PlanningDocument;
use App\Models\RegionalIndex;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BapperidaDataSeeder extends Seeder
{
    /**
     * Seed core BAPPERIDA domain data.
     */
    public function run(): void
    {
        $superAdmin = User::first();

        // 1. Kategori Dokumen (Perencanaan, Kajian, Analisis & 4 Laporan Indeks)
        $docCategories = [
            [
                'name' => 'Dokumen Perencanaan',
                'slug' => 'dokumen-perencanaan',
                'description' => 'Dokumen perencanaan induk daerah meliputi RPJPD, RPJMD, RKPD, Renstra, dan Renja.',
            ],
            [
                'name' => 'Dokumen Kajian',
                'slug' => 'dokumen-kajian',
                'description' => 'Kajian strategis kebijakan daerah, kelayakan program, dan naskah akademik.',
            ],
            [
                'name' => 'Dokumen Analisis',
                'slug' => 'dokumen-analisis',
                'description' => 'Analisis data spasial, ekonomi makro daerah, dan evaluasi capaian pembangunan.',
            ],
            [
                'name' => 'Laporan Akuntabilitas',
                'slug' => 'laporan-akuntabilitas',
                'description' => 'Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP) dan evaluasi SAKIP.',
            ],
            [
                'name' => 'Indeks Inovasi Daerah (IID)',
                'slug' => 'laporan-iid',
                'description' => 'Laporan pengukuran kematangan dan dampak ekosistem inovasi daerah oleh Kemendagri RI.',
            ],
            [
                'name' => 'Indeks Daya Saing Daerah (IDSD)',
                'slug' => 'laporan-idsd',
                'description' => 'Laporan pengukuran produktivitas dan pilar daya saing daerah oleh BRIN.',
            ],
            [
                'name' => 'Indeks Pengelolaan Keuangan Daerah (IPKD)',
                'slug' => 'laporan-ipkd',
                'description' => 'Laporan evaluasi transparansi, akuntabilitas, dan efisiensi fiskal keuangan daerah.',
            ],
            [
                'name' => 'Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP)',
                'slug' => 'laporan-lakip',
                'description' => 'Laporan tahunan pertanggungjawaban kinerja instansi pemerintah (LAKIP / SAKIP).',
            ],
        ];

        $savedDocCats = [];
        foreach ($docCategories as $cat) {
            $savedDocCats[$cat['slug']] = DocumentCategory::firstOrCreate(['slug' => $cat['slug']], $cat);
        }

        // 2. Dokumen Perencanaan Riil/Contoh
        $documents = [
            [
                'category_id' => $savedDocCats['dokumen-perencanaan']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Rencana Kerja Pemerintah Daerah (RKPD) Kabupaten Pringsewu Tahun 2026',
                'slug' => Str::slug('Rencana Kerja Pemerintah Daerah (RKPD) Kabupaten Pringsewu Tahun 2026'),
                'year' => 2026,
                'document_number' => 'Perbup No. 18 Tahun 2025',
                'description' => 'Dokumen RKPD memuat rancangan kerangka ekonomi daerah, prioritas pembangunan daerah, serta rencana kerja dan pendanaan untuk tahun 2026.',
                'file_name' => 'RKPD_Kabupaten_Pringsewu_2026.pdf',
                'file_size' => 14250000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 184,
                'is_published' => true,
                'published_at' => now()->subDays(10),
            ],
            [
                'category_id' => $savedDocCats['dokumen-perencanaan']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Rencana Pembangunan Jangka Menengah Daerah (RPJMD) Kabupaten Pringsewu 2025-2029',
                'slug' => Str::slug('Rencana Pembangunan Jangka Menengah Daerah (RPJMD) Kabupaten Pringsewu 2025-2029'),
                'year' => 2025,
                'document_number' => 'Perda No. 04 Tahun 2025',
                'description' => 'Arah kebijakan dan strategi pembangunan lima tahunan Kabupaten Pringsewu menuju daerah yang berdaya saing, agraris mandiri, dan berkeadaban.',
                'file_name' => 'RPJMD_Pringsewu_2025_2029.pdf',
                'file_size' => 28400000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 420,
                'is_published' => true,
                'published_at' => now()->subDays(30),
            ],
            [
                'category_id' => $savedDocCats['dokumen-perencanaan']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Rencana Strategis (Renstra) BAPPERIDA Kabupaten Pringsewu Tahun 2025-2029',
                'slug' => Str::slug('Rencana Strategis (Renstra) BAPPERIDA Kabupaten Pringsewu Tahun 2025-2029'),
                'year' => 2025,
                'document_number' => 'Kepka Bapperida No. 02/2025',
                'description' => 'Renstra BAPPERIDA memuat visi teknis perencanaan, target indeks inovasi, dan roadmap riset daerah.',
                'file_name' => 'Renstra_Bapperida_Pringsewu_2025_2029.pdf',
                'file_size' => 8600000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 95,
                'is_published' => true,
                'published_at' => now()->subDays(20),
            ],
            [
                'category_id' => $savedDocCats['dokumen-perencanaan']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Rencana Pembangunan Jangka Panjang Daerah (RPJPD) Kabupaten Pringsewu 2025-2045',
                'slug' => Str::slug('Rencana Pembangunan Jangka Panjang Daerah RPJPD Kabupaten Pringsewu 2025 2045'),
                'year' => 2025,
                'document_number' => 'Perda No. 01 Tahun 2025',
                'description' => 'Visi haluan besar pembangunan Pringsewu 20 tahun ke depan menuju Kabupaten Berdaya Saing, Harmonis, dan Berkelanjutan.',
                'file_name' => 'RPJPD_Kabupaten_Pringsewu_2025_2045.pdf',
                'file_size' => 32500000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 310,
                'is_published' => true,
                'published_at' => now()->subDays(40),
            ],
            [
                'category_id' => $savedDocCats['dokumen-perencanaan']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Rencana Kerja (Renja) BAPPERIDA Kabupaten Pringsewu Tahun 2026',
                'slug' => Str::slug('Rencana Kerja Renja BAPPERIDA Kabupaten Pringsewu Tahun 2026'),
                'year' => 2026,
                'document_number' => 'Renja-BAPPERIDA-2026',
                'description' => 'Matriks target program kerja teknis operasional 5 bidang perencana dan kesekretariatan BAPPERIDA tahun anggaran 2026.',
                'file_name' => 'Renja_BAPPERIDA_Pringsewu_2026.pdf',
                'file_size' => 6700000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 140,
                'is_published' => true,
                'published_at' => now()->subDays(5),
            ],
            [
                'category_id' => $savedDocCats['dokumen-perencanaan']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Perubahan Rencana Kerja Pemerintah Daerah (P-RKPD) Kabupaten Pringsewu Tahun 2025',
                'slug' => Str::slug('Perubahan Rencana Kerja Pemerintah Daerah P-RKPD Kabupaten Pringsewu Tahun 2025'),
                'year' => 2025,
                'document_number' => 'Perbup No. 24 Tahun 2025',
                'description' => 'Penyesuaian target indikator kinerja makro, realokasi belanja prioritas daerah, dan evaluasi capaian semester I tahun 2025.',
                'file_name' => 'P-RKPD_Kabupaten_Pringsewu_2025.pdf',
                'file_size' => 16800000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 195,
                'is_published' => true,
                'published_at' => now()->subDays(60),
            ],
            [
                'category_id' => $savedDocCats['dokumen-kajian']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Kajian Strategis Penanganan Kemiskinan Ekstrem dan Stunting Berbasis Spasial',
                'slug' => Str::slug('Kajian Strategis Penanganan Kemiskinan Ekstrem dan Stunting Berbasis Spasial'),
                'year' => 2025,
                'document_number' => 'Naskah Akademik 08/RIDA/2025',
                'description' => 'Kajian kolaboratif Bapperida bersama akademisi untuk pemetaan intervensi gizi terpadu di 9 kecamatan.',
                'file_name' => 'Kajian_Stunting_Kemiskinan_Pringsewu_2025.pdf',
                'file_size' => 5200000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 112,
                'is_published' => true,
                'published_at' => now()->subDays(15),
            ],
            [
                'category_id' => $savedDocCats['dokumen-kajian']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Kajian Kelayakan Pengembangan Kawasan Sentra Agribisnis Terpadu Pringsewu',
                'slug' => Str::slug('Kajian Kelayakan Pengembangan Kawasan Sentra Agribisnis Terpadu Pringsewu'),
                'year' => 2025,
                'document_number' => 'Kajian Teknis 12/PSDA/2025',
                'description' => 'Studi kelayakan rantai pasok hilirisasi komoditas beras, hortikultura, dan perkebunan terintegrasi di Kabupaten Pringsewu.',
                'file_name' => 'Kajian_Agribisnis_Terpadu_Pringsewu_2025.pdf',
                'file_size' => 7400000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 88,
                'is_published' => true,
                'published_at' => now()->subDays(18),
            ],
            [
                'category_id' => $savedDocCats['dokumen-analisis']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Analisis Ekonomi Makro dan Proyeksi Pertumbuhan PDRB Kabupaten Pringsewu 2025-2029',
                'slug' => Str::slug('Analisis Ekonomi Makro dan Proyeksi Pertumbuhan PDRB Kabupaten Pringsewu 2025-2029'),
                'year' => 2025,
                'document_number' => 'Analisis-Makro-01/PPE/2025',
                'description' => 'Analisis komparatif laju pertumbuhan ekonomi daerah, tingkat inflasi, penyerapan tenaga kerja, dan proyeksi PDRB sektoral.',
                'file_name' => 'Analisis_Ekonomi_Makro_Pringsewu_2025_2029.pdf',
                'file_size' => 9100000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 143,
                'is_published' => true,
                'published_at' => now()->subDays(12),
            ],
            [
                'category_id' => $savedDocCats['dokumen-analisis']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Analisis Spasial Daya Dukung Daya Tampung Lingkungan Hidup (D3TLH) Pringsewu',
                'slug' => Str::slug('Analisis Spasial Daya Dukung Daya Tampung Lingkungan Hidup D3TLH Pringsewu'),
                'year' => 2025,
                'document_number' => 'Analisis-Spasial-05/IPW/2025',
                'description' => 'Analisis spasial kesesuaian lahan, ketersediaan air baku, dan daya tampung lingkungan hidup untuk mendukung revisi RTRW.',
                'file_name' => 'Analisis_Spasial_D3TLH_Pringsewu_2025.pdf',
                'file_size' => 11800000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 105,
                'is_published' => true,
                'published_at' => now()->subDays(25),
            ],
            [
                'category_id' => $savedDocCats['laporan-akuntabilitas']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP) BAPPERIDA 2025',
                'slug' => Str::slug('Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP) BAPPERIDA 2025'),
                'year' => 2025,
                'document_number' => 'LAKIP-BAPPERIDA-2025',
                'description' => 'Laporan pertanggungjawaban pencapaian sasaran strategis, efisiensi anggaran, dan realisasi kinerja BAPPERIDA.',
                'file_name' => 'LAKIP_BAPPERIDA_2025.pdf',
                'file_size' => 6700000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 76,
                'is_published' => true,
                'published_at' => now()->subDays(5),
            ],

            // 4 Kategori Laporan Indeks & LAKIP Resmi
            // Laporan IID
            [
                'category_id' => $savedDocCats['laporan-iid']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Hasil Pengukuran Indeks Inovasi Daerah (IID) Kabupaten Pringsewu Tahun 2025',
                'slug' => Str::slug('Laporan Hasil Pengukuran Indeks Inovasi Daerah IID Kabupaten Pringsewu Tahun 2025'),
                'year' => 2025,
                'document_number' => 'Kepmendagri No. 100.4.3-128/2025',
                'description' => 'Dokumen resmi hasil evaluasi dan penetapan Kabupaten Pringsewu berpredikat Sangat Inovatif dengan capaian skor 62,45 beserta rincian 58 proposal inovasi daerah.',
                'file_name' => 'Laporan_Indeks_Inovasi_Daerah_Pringsewu_2025.pdf',
                'file_size' => 9850000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 234,
                'is_published' => true,
                'published_at' => now()->subDays(15),
            ],
            [
                'category_id' => $savedDocCats['laporan-iid']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Kematangan Ekosistem Riset dan Inovasi Daerah Pringsewu Tahun 2024',
                'slug' => Str::slug('Laporan Kematangan Ekosistem Riset dan Inovasi Daerah Pringsewu Tahun 2024'),
                'year' => 2024,
                'document_number' => 'Laporan-IID-2024/RIDA',
                'description' => 'Evaluasi penerapan inovasi tata kelola pemerintahan desa dan inovasi digital pelayanan publik Kabupaten Pringsewu tahun 2024.',
                'file_name' => 'Laporan_IID_Pringsewu_2024.pdf',
                'file_size' => 8400000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 189,
                'is_published' => true,
                'published_at' => now()->subMonths(12),
            ],
            [
                'category_id' => $savedDocCats['laporan-iid']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Buku Profil Inovasi Pelayanan Publik dan Tata Kelola Pekon Pringsewu 2023',
                'slug' => Str::slug('Buku Profil Inovasi Pelayanan Publik dan Tata Kelola Pekon Pringsewu 2023'),
                'year' => 2023,
                'document_number' => 'Buku-Inovasi-Pringsewu-2023',
                'description' => 'Kompilasi inovasi unggulan berbasis kearifan lokal bambu, agribisnis pekon, dan kemudahan layanan administrasi kependudukan.',
                'file_name' => 'Buku_Profil_Inovasi_Pringsewu_2023.pdf',
                'file_size' => 12300000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 142,
                'is_published' => true,
                'published_at' => now()->subMonths(24),
            ],

            // Laporan IDSD
            [
                'category_id' => $savedDocCats['laporan-idsd']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Analisis Indeks Daya Saing Daerah (IDSD) Kabupaten Pringsewu Tahun 2025',
                'slug' => Str::slug('Laporan Analisis Indeks Daya Saing Daerah IDSD Kabupaten Pringsewu Tahun 2025'),
                'year' => 2025,
                'document_number' => 'BRIN-IDSD/PSW/2025',
                'description' => 'Laporan pengukuran komprehensif Badan Riset dan Inovasi Nasional (BRIN) dengan skor IDSD 3,42 (Kategori Tinggi) meliputi 4 komponen dan 12 pilar daya saing.',
                'file_name' => 'Laporan_IDSD_Kabupaten_Pringsewu_2025.pdf',
                'file_size' => 11200000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 178,
                'is_published' => true,
                'published_at' => now()->subDays(18),
            ],
            [
                'category_id' => $savedDocCats['laporan-idsd']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Pengukuran Produktivitas dan Daya Saing Wilayah Pringsewu Tahun 2024',
                'slug' => Str::slug('Laporan Pengukuran Produktivitas dan Daya Saing Wilayah Pringsewu Tahun 2024'),
                'year' => 2024,
                'document_number' => 'IDSD-PSW-2024',
                'description' => 'Analisis komparatif pilar ekosistem bisnis, dinamika pasar tenaga kerja, dan adopsi TIK di Kabupaten Pringsewu.',
                'file_name' => 'Laporan_IDSD_Pringsewu_2024.pdf',
                'file_size' => 7600000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 155,
                'is_published' => true,
                'published_at' => now()->subMonths(11),
            ],
            [
                'category_id' => $savedDocCats['laporan-idsd']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Kajian Pilar Lingkungan Pendukung Daya Saing Ekonomi Pringsewu 2023',
                'slug' => Str::slug('Kajian Pilar Lingkungan Pendukung Daya Saing Ekonomi Pringsewu 2023'),
                'year' => 2023,
                'document_number' => 'IDSD-Kajian-2023',
                'description' => 'Kajian mendalam stabilitas kelembagaan, infrastruktur dasar, dan kesiapan sektor ekonomi kerakyatan menghadapi pasar bebas.',
                'file_name' => 'Kajian_Daya_Saing_Pringsewu_2023.pdf',
                'file_size' => 6900000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 110,
                'is_published' => true,
                'published_at' => now()->subMonths(22),
            ],

            // Laporan IPKD
            [
                'category_id' => $savedDocCats['laporan-ipkd']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Hasil Pengukuran Indeks Pengelolaan Keuangan Daerah (IPKD) Tahun 2025',
                'slug' => Str::slug('Laporan Hasil Pengukuran Indeks Pengelolaan Keuangan Daerah IPKD Tahun 2025'),
                'year' => 2025,
                'document_number' => 'Kepka-IPKD-PSW-2025',
                'description' => 'Laporan evaluasi Kemendagri dan BPKP atas kualitas pengelolaan keuangan Pringsewu dengan skor 84,10 (Kategori Baik) mencakup keselarasan dokumen perencanaan dan penganggaran.',
                'file_name' => 'Laporan_IPKD_Kabupaten_Pringsewu_2025.pdf',
                'file_size' => 10500000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 205,
                'is_published' => true,
                'published_at' => now()->subDays(22),
            ],
            [
                'category_id' => $savedDocCats['laporan-ipkd']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Evaluasi Keselarasan Anggaran dan Efisiensi Fiskal Daerah Pringsewu 2024',
                'slug' => Str::slug('Laporan Evaluasi Keselarasan Anggaran dan Efisiensi Fiskal Daerah Pringsewu 2024'),
                'year' => 2024,
                'document_number' => 'IPKD-Fiskal-2024',
                'description' => 'Pengukuran dimensi transparansi pengelolaan keuangan, penyerapan anggaran belanja modal, dan kondisi keuangan daerah.',
                'file_name' => 'Evaluasi_Fiskal_IPKD_2024.pdf',
                'file_size' => 8100000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 160,
                'is_published' => true,
                'published_at' => now()->subMonths(10),
            ],
            [
                'category_id' => $savedDocCats['laporan-ipkd']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Keterbukaan dan Alokasi Belanja Modal Pembangunan Pringsewu 2023',
                'slug' => Str::slug('Laporan Keterbukaan dan Alokasi Belanja Modal Pembangunan Pringsewu 2023'),
                'year' => 2023,
                'document_number' => 'IPKD-Transparansi-2023',
                'description' => 'Laporan kinerja pemenuhan belanja wajib (mandatory spending) urusan pendidikan, kesehatan, dan infrastruktur.',
                'file_name' => 'Laporan_Transparansi_IPKD_2023.pdf',
                'file_size' => 7400000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 125,
                'is_published' => true,
                'published_at' => now()->subMonths(21),
            ],

            // Laporan LAKIP
            [
                'category_id' => $savedDocCats['laporan-lakip']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP) BAPPERIDA Tahun 2025',
                'slug' => Str::slug('Laporan Akuntabilitas Kinerja Instansi Pemerintah LAKIP BAPPERIDA Tahun 2025'),
                'year' => 2025,
                'document_number' => 'LAKIP-BAPPERIDA-2025-FINAL',
                'description' => 'Laporan resmi akuntabilitas kinerja BAPPERIDA Pringsewu dengan predikat A (Nilai 82,30) berdasarkan evaluasi KemenPAN-RB.',
                'file_name' => 'LAKIP_BAPPERIDA_Pringsewu_2025.pdf',
                'file_size' => 14800000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 312,
                'is_published' => true,
                'published_at' => now()->subDays(10),
            ],
            [
                'category_id' => $savedDocCats['laporan-lakip']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Kinerja Instansi Pemerintah (LKjIP) BAPPERIDA Kabupaten Pringsewu Tahun 2024',
                'slug' => Str::slug('Laporan Kinerja Instansi Pemerintah LKjIP BAPPERIDA Kabupaten Pringsewu Tahun 2024'),
                'year' => 2024,
                'document_number' => 'LKjIP-BAPPERIDA-2024',
                'description' => 'Pertanggungjawaban sasaran strategis, efisiensi pagu anggaran, serta capaian indikator kinerja utama Bapperida tahun 2024.',
                'file_name' => 'LKjIP_BAPPERIDA_Pringsewu_2024.pdf',
                'file_size' => 11900000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 220,
                'is_published' => true,
                'published_at' => now()->subMonths(11),
            ],
            [
                'category_id' => $savedDocCats['laporan-lakip']->id,
                'user_id' => $superAdmin?->id,
                'title' => 'Laporan Evaluasi Perjanjian Kinerja dan Capaian Target Renstra BAPPERIDA 2023',
                'slug' => Str::slug('Laporan Evaluasi Perjanjian Kinerja dan Capaian Target Renstra BAPPERIDA 2023'),
                'year' => 2023,
                'document_number' => 'LAKIP-PK-2023',
                'description' => 'Realisasi perjanjian kinerja aparatur perencana dan capaian target rencana strategis lima tahunan Bapperida.',
                'file_name' => 'Laporan_PK_LAKIP_2023.pdf',
                'file_size' => 9100000,
                'file_mime' => 'application/pdf',
                'downloads_count' => 175,
                'is_published' => true,
                'published_at' => now()->subMonths(23),
            ],
        ];

        foreach ($documents as $doc) {
            PlanningDocument::firstOrCreate(['slug' => $doc['slug']], $doc);
        }

        // 3. Kategori Berita 6 Bidang Resmi
        $newsCategories = [
            [
                'name' => 'Sekretariat / Umum',
                'code' => 'UMUM',
                'slug' => 'umum',
                'description' => 'Kegiatan kesekretariatan, kepegawaian, keuangan, dan tata usaha Bapperida.',
                'color' => 'slate',
            ],
            [
                'name' => 'Perencanaan Pengendalian dan Evaluasi',
                'code' => 'PPE',
                'slug' => 'ppe',
                'description' => 'Penyusunan RPJMD, RKPD, Musrenbang, dan evaluasi berkala capaian pembangunan.',
                'color' => 'teal',
            ],
            [
                'name' => 'Pemerintahan dan Pembangunan Manusia',
                'code' => 'PPM',
                'slug' => 'ppm',
                'description' => 'Perencanaan bidang pendidikan, kesehatan, sosial, ketenagakerjaan, dan aparatur.',
                'color' => 'blue',
            ],
            [
                'name' => 'Perekonomian dan Sumber Daya Alam',
                'code' => 'PSDA',
                'slug' => 'psda',
                'description' => 'Pengembangan sentra UMKM, pertanian, perikanan, perdagangan, dan lingkungan hidup.',
                'color' => 'emerald',
            ],
            [
                'name' => 'Infrastruktur dan Pengembangan Wilayah',
                'code' => 'IPW',
                'slug' => 'ipw',
                'description' => 'Tata ruang kota, konektivitas jalan, sanitasi, perumahan, dan utilitas daerah.',
                'color' => 'amber',
            ],
            [
                'name' => 'Riset dan Inovasi Daerah',
                'code' => 'RIDA',
                'slug' => 'rida',
                'description' => 'Inovasi daerah, ekosistem riset, lomba kreativitas inovasi, dan indeks IID/IDSD.',
                'color' => 'purple',
            ],
        ];

        $savedNewsCats = [];
        foreach ($newsCategories as $cat) {
            $savedNewsCats[$cat['code']] = NewsCategory::firstOrCreate(['code' => $cat['code']], $cat);
        }

        // 4. Berita / Artikel Publikasi per Bidang (Magazine Style)
        $articles = [
            // UMUM
            [
                'category_id' => $savedNewsCats['UMUM']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Penguatan Tata Kelola Reformasi Birokrasi dan Peningkatan Kapasitas SDM Bapperida Pringsewu',
                'slug' => Str::slug('Penguatan Tata Kelola Reformasi Birokrasi dan Peningkatan Kapasitas SDM Bapperida Pringsewu'),
                'excerpt' => 'Sekretariat BAPPERIDA menyelenggarakan lokakarya internal untuk memperkuat integritas aparatur, pengelolaan arsip digital, dan kedisiplinan kinerja.',
                'content' => '<p>Sekretariat Badan Perencanaan Pembangunan, Riset dan Inovasi Daerah (BAPPERIDA) Kabupaten Pringsewu terus memacu profesionalisme aparatur perencana melalui serangkaian bimbingan teknis dan implementasi manajemen talenta terpadu.</p><p>Sekretaris BAPPERIDA menekankan bahwa fondasi perencanaan yang kuat berakar dari akuntabilitas tata kelola keuangan, ketepatan administrasi, serta budaya kerja yang berorientasi pada pelayanan prima kepada seluruh OPD dan masyarakat.</p>',
                'views_count' => 285,
                'is_published' => true,
                'published_at' => now()->subDays(3),
            ],
            [
                'category_id' => $savedNewsCats['UMUM']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Implementasi Sistem Akuntabilitas Kinerja Instansi Pemerintah Berbasis Digital',
                'slug' => Str::slug('Implementasi Sistem Akuntabilitas Kinerja Instansi Pemerintah Berbasis Digital'),
                'excerpt' => 'Optimalisasi aplikasi e-SAKIP mendorong transparansi pelaporan capaian program dan efisiensi serapan anggaran di lingkungan Bapperida.',
                'content' => '<p>Dalam upaya mendukung transformasi digital birokrasi pemerintahan, Subbagian Perencanaan dan Keuangan BAPPERIDA mengintegrasikan modul e-SAKIP dalam pemantauan kinerja harian dan bulanan setiap bidang perencanaan.</p><p>Langkah ini menempatkan BAPPERIDA sebagai salah satu pelopor keterbukaan informasi dan akuntabilitas kinerja di tingkat Pemerintah Kabupaten Pringsewu.</p>',
                'views_count' => 190,
                'is_published' => true,
                'published_at' => now()->subDays(8),
            ],

            // PPE
            [
                'category_id' => $savedNewsCats['PPE']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'BAPPERIDA Pringsewu Gelar Forum Konsultasi Publik Rancangan Awal RKPD 2026',
                'slug' => Str::slug('BAPPERIDA Pringsewu Gelar Forum Konsultasi Publik Rancangan Awal RKPD 2026'),
                'excerpt' => 'Forum konsultasi publik bertujuan menghimpun aspirasi pemangku kepentingan dan menyelaraskan prioritas pembangunan Kabupaten Pringsewu tahun 2026.',
                'content' => '<p>Badan Perencanaan Pembangunan, Riset dan Inovasi Daerah (BAPPERIDA) Kabupaten Pringsewu menggelar Forum Konsultasi Publik Rancangan Awal Rencana Kerja Pemerintah Daerah (RKPD) Tahun 2026 secara hibrid yang dihadiri oleh seluruh pimpinan perangkat daerah, akademisi, tokoh masyarakat, dan perwakilan generasi muda.</p><p>Kepala BAPPERIDA menegaskan pentingnya kolaborasi pentahelix untuk memastikan pembangunan yang inklusif, adaptif terhadap perubahan iklim, dan berorientasi pada peningkatan kesejahteraan masyarakat di seluruh kecamatan se-Kabupaten Pringsewu.</p>',
                'views_count' => 442,
                'is_published' => true,
                'published_at' => now()->subDays(2),
            ],
            [
                'category_id' => $savedNewsCats['PPE']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Rapat Koordinasi Evaluasi Triwulanan Realisasi RKPD dan Capaian Sasaran Makro',
                'slug' => Str::slug('Rapat Koordinasi Evaluasi Triwulanan Realisasi RKPD dan Capaian Sasaran Makro'),
                'excerpt' => 'Bidang PPE memaparkan progres indikator makro pembangunan ekonomi, laju inflasi daerah, dan konsistensi perencanaan anggaran daerah.',
                'content' => '<p>Bidang Perencanaan, Pengendalian dan Evaluasi (PPE) memimpin rapat koordinasi pengendalian dan evaluasi pelaksanaan rencana pembangunan daerah bersama tim pengendali perangkat daerah.</p><p>Evaluasi menyeluruh dilakukan guna memitigasi kendala pelaksanaan di lapangan dan memastikan target tahun berjalan tercapai sesuai koridor waktu yang ditetapkan.</p>',
                'views_count' => 310,
                'is_published' => true,
                'published_at' => now()->subDays(6),
            ],

            // PPM
            [
                'category_id' => $savedNewsCats['PPM']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Rembuk Stunting Pringsewu 2025: Penguatan Konvergensi Intervensi Gizi Spesifik dan Sensitif',
                'slug' => Str::slug('Rembuk Stunting Pringsewu 2025 Penguatan Konvergensi Intervensi Gizi Spesifik dan Sensitif'),
                'excerpt' => 'Bidang PPM menyatukan langkah lintas sektor perangkat daerah, puskesmas, dan kader posyandu untuk menuntaskan stunting hingga ke tingkat pekon.',
                'content' => '<p>Bidang Pemerintahan dan Pembangunan Manusia (PPM) BAPPERIDA memfasilitasi gelaran Rembuk Stunting Tingkat Kabupaten Pringsewu sebagai wujud komitmen zero stunting.</p><p>Fokus utama mencakup pemetaan sasaran keluarga berisiko stunting, penyaluran pangan bergizi, serta sanitasi total berbasis masyarakat (STBM) yang terintegrasi di 126 pekon dan 5 kelurahan.</p>',
                'views_count' => 512,
                'is_published' => true,
                'published_at' => now()->subDays(1),
            ],
            [
                'category_id' => $savedNewsCats['PPM']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Peningkatan Indeks Pembangunan Manusia (IPM) Pringsewu Melalui Pemerataan Layanan Dasar',
                'slug' => Str::slug('Peningkatan Indeks Pembangunan Manusia IPM Pringsewu Melalui Pemerataan Layanan Dasar'),
                'excerpt' => 'Pringsewu konsisten mencatatkan IPM tertinggi di antara kabupaten se-Provinsi Lampung berkat sinergi pendidikan dan perlindungan sosial.',
                'content' => '<p>Dengan angka IPM mencapai 72,85, Kabupaten Pringsewu terus memantapkan posisinya sebagai daerah dengan kualitas manusia yang unggul. Bidang PPM merumuskan langkah afirmasi untuk memastikan angka harapan sekolah dan usia harapan hidup terus meningkat di masa mendatang.</p>',
                'views_count' => 378,
                'is_published' => true,
                'published_at' => now()->subDays(5),
            ],

            // PSDA
            [
                'category_id' => $savedNewsCats['PSDA']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Penguatan Ketahanan Pangan Melalui Hilirisasi Komoditas Pertanian Unggulan',
                'slug' => Str::slug('Penguatan Ketahanan Pangan Melalui Hilirisasi Komoditas Pertanian Unggulan'),
                'excerpt' => 'Bidang PSDA merumuskan strategi penguatan rantai pasok komoditas beras, kakao, dan hortikultura di sentra agribisnis Pringsewu.',
                'content' => '<p>Sebagai lumbung pangan potensial di Provinsi Lampung, Kabupaten Pringsewu terus memacu produktivitas petani lewat program hilirisasi dan digitalisasi pemasaran hasil panen yang diintegrasikan dalam dokumen perencanaan tahunan.</p>',
                'views_count' => 295,
                'is_published' => true,
                'published_at' => now()->subDays(9),
            ],
            [
                'category_id' => $savedNewsCats['PSDA']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Pengembangan Ekosistem UMKM dan Klaster Industri Kreatif Berbasis Potensi Lokal',
                'slug' => Str::slug('Pengembangan Ekosistem UMKM dan Klaster Industri Kreatif Berbasis Potensi Lokal'),
                'excerpt' => 'Fasilitasi permodalan, perizinan berusaha mudah, dan promosi kain Tapis khas Pringsewu diangkat sebagai pilar ekonomi kerakyatan.',
                'content' => '<p>Bidang Perekonomian dan Sumber Daya Alam (PSDA) menginisiasi program pemberdayaan terpadu bagi kelompok pengrajin tapis dan industri pangan olahan bambu guna memperluas penetrasi pasar regional maupun internasional.</p>',
                'views_count' => 240,
                'is_published' => true,
                'published_at' => now()->subDays(11),
            ],

            // IPW
            [
                'category_id' => $savedNewsCats['IPW']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Sinkronisasi Rencana Tata Ruang Wilayah (RTRW) Pringsewu Dukung Kawasan Industri Hijau',
                'slug' => Str::slug('Sinkronisasi Rencana Tata Ruang Wilayah RTRW Pringsewu Dukung Kawasan Industri Hijau'),
                'excerpt' => 'Bidang IPW mematangkan revisi RTRW untuk menjamin kepastian investasi dan perlindungan lahan pertanian pangan berkelanjutan.',
                'content' => '<p>Bidang Infrastruktur dan Pengembangan Wilayah (IPW) BAPPERIDA memfasilitasi rapat koordinasi penataan ruang bersama kementerian terkait. Penyesuaian RTRW ini difokuskan pada penguatan koridor ekonomi antardaerah dengan tetap mempertahankan lahan sawah dilindungi (LSD).</p>',
                'views_count' => 310,
                'is_published' => true,
                'published_at' => now()->subDays(7),
            ],
            [
                'category_id' => $savedNewsCats['IPW']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Peningkatan Akses Sanitasi Layak dan Air Bersih Menuju Permukiman Berkelanjutan',
                'slug' => Str::slug('Peningkatan Akses Sanitasi Layak dan Air Bersih Menuju Permukiman Berkelanjutan'),
                'excerpt' => 'Bidang IPW mengawal rencana induk penyediaan air minum (RISPAM) dan pembangunan infrastruktur persampahan ramah lingkungan.',
                'content' => '<p>Melalui perencanaan infrastruktur yang terukur, BAPPERIDA memastikan ketersediaan akses sarana sanitasi dasar dan jaringan pipa air minum perpipaan bagi masyarakat perkotaan dan perdesaan secara berkeadilan.</p>',
                'views_count' => 220,
                'is_published' => true,
                'published_at' => now()->subDays(12),
            ],

            // RIDA
            [
                'category_id' => $savedNewsCats['RIDA']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Kabupaten Pringsewu Raih Predikat Sangat Inovatif pada Indeks Inovasi Daerah 2025',
                'slug' => Str::slug('Kabupaten Pringsewu Raih Predikat Sangat Inovatif pada Indeks Inovasi Daerah 2025'),
                'excerpt' => 'Dengan skor 62,45, Kabupaten Pringsewu kembali menorehkan prestasi gemilang dalam penilaian Indeks Inovasi Daerah oleh Kemendagri RI.',
                'content' => '<p>Kementerian Dalam Negeri Republik Indonesia secara resmi merilis hasil pengukuran Indeks Inovasi Daerah (IID) tahun 2025. Kabupaten Pringsewu sukses meraih predikat Sangat Inovatif dengan skor 62,45.</p><p>Capaian ini didorong oleh penerapan puluhan inovasi layanan publik berbasis digital, inovasi tata kelola pemerintahan desa, dan kemudahan akses data untuk masyarakat.</p>',
                'views_count' => 588,
                'is_published' => true,
                'published_at' => now()->subDays(4),
            ],
            [
                'category_id' => $savedNewsCats['RIDA']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Peluncuran Kompetisi Inovasi Daerah (KID) Pringsewu 2026: Ruang Riset dan Gagasan Kreatif',
                'slug' => Str::slug('Peluncuran Kompetisi Inovasi Daerah KID Pringsewu 2026 Ruang Riset dan Gagasan Kreatif'),
                'excerpt' => 'Bidang Riset dan Inovasi Daerah mengajak seluruh pelajar, mahasiswa, akademisi, dan ASN untuk melahirkan inovasi solutif bagi Pringsewu.',
                'content' => '<p>Bidang RIDA BAPPERIDA membuka pendaftaran Kompetisi Inovasi Daerah (KID) 2026 dengan tema "Inovasi Berkelanjutan untuk Pringsewu Sejahtera". Pemenang akan mendapatkan pendanaan riset prototipe dan fasilitasi pendaftaran Hak Kekayaan Intelektual (HAKI).</p>',
                'views_count' => 415,
                'is_published' => true,
                'published_at' => now()->subDays(10),
            ],

            // Additional News per Bidang for Rich Magazine Layout
            [
                'category_id' => $savedNewsCats['UMUM']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Penguatan Pelayanan Informasi Publik dan Digitalisasi Arsip Perencanaan BAPPERIDA',
                'slug' => Str::slug('Penguatan Pelayanan Informasi Publik dan Digitalisasi Arsip Perencanaan BAPPERIDA'),
                'excerpt' => 'Subbag Umum mempercepat transformasi e-office dan keterbukaan akses dokumen perencanaan melalui portal Satu Data terpadu.',
                'content' => '<p>Sekretariat BAPPERIDA Kabupaten Pringsewu terus membenahi standar layanan informasi publik. Pemanfaatan sistem digitalisasi arsip memungkinkan masyarakat mengakses ringkasan eksekutif dokumen perencanaan secara cepat, transparan, dan terverifikasi.</p>',
                'views_count' => 320,
                'is_published' => true,
                'published_at' => now()->subHours(18),
            ],
            [
                'category_id' => $savedNewsCats['PPE']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Harmonisasi Target RPJMD 2025-2029 dan Evaluasi Capaian Indikator Sasaran Makro Daerah',
                'slug' => Str::slug('Harmonisasi Target RPJMD 2025 2029 dan Evaluasi Capaian Indikator Sasaran Makro Daerah'),
                'excerpt' => 'Bidang PPE mematangkan penyelarasan indikator pertumbuhan ekonomi makro, inflasi terkendali, dan angka kemiskinan ekstrem.',
                'content' => '<p>Penyusunan kerangka target 5 tahunan RPJMD Kabupaten Pringsewu 2025-2029 memasuki tahap uji publik. Bidang PPE menegaskan seluruh program perangkat daerah harus inline dengan tema pembangunan Lampung Maju dan Mandiri.</p>',
                'views_count' => 480,
                'is_published' => true,
                'published_at' => now()->subHours(12),
            ],
            [
                'category_id' => $savedNewsCats['PPM']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Peluang Kerja Generasi Muda: Integrasi Pelatihan Vokasi SMK dan Kebutuhan Industri Pringsewu',
                'slug' => Str::slug('Peluang Kerja Generasi Muda Integrasi Pelatihan Vokasi SMK dan Kebutuhan Industri Pringsewu'),
                'excerpt' => 'Bidang PPM menyinergikan link and match kurikulum SMK dengan sentra industri kreatif dan agribisnis modern.',
                'content' => '<p>Dalam upaya menekan tingkat pengangguran terbuka (TPT), Bidang PPM BAPPERIDA menginisiasi forum pentahelix bersama dunia usaha, dunia industri, dan sekolah kejuruan di Pringsewu untuk mencetak SDM berdaya saing global.</p>',
                'views_count' => 395,
                'is_published' => true,
                'published_at' => now()->subHours(8),
            ],
            [
                'category_id' => $savedNewsCats['PSDA']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Strategi Penguatan Pasar Komoditas Organik dan Produk Olahan Bambu Unggulan Pringsewu',
                'slug' => Str::slug('Strategi Penguatan Pasar Komoditas Organik dan Produk Olahan Bambu Unggulan Pringsewu'),
                'excerpt' => 'Bidang PSDA mendorong hilirisasi ekonomi hijau berbasis kearifan lokal bambu dan sertifikasi pangan organik berskala nasional.',
                'content' => '<p>Kabupaten Pringsewu memiliki potensi besar sebagai sentra kerajinan bambu dan pertanian ramah lingkungan. Bidang PSDA merancang fasilitasi sertifikasi organik serta kemitraan ritel modern demi menembus pasar ekspor.</p>',
                'views_count' => 450,
                'is_published' => true,
                'published_at' => now()->subHours(4),
            ],
            [
                'category_id' => $savedNewsCats['IPW']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Optimalisasi Jaringan Drainase dan Manajemen Risiko Banjir Kawasan Perkotaan Pringsewu',
                'slug' => Str::slug('Optimalisasi Jaringan Drainase dan Manajemen Risiko Banjir Kawasan Perkotaan Pringsewu'),
                'excerpt' => 'Bidang IPW merumuskan masterplan drainase perkotaan terpadu dan revitalisasi sempadan sungai untuk perlindungan lingkungan.',
                'content' => '<p>Mengantisipasi perubahan iklim ekstrem, Bidang Infrastruktur dan Pengembangan Wilayah memetakan titik resapan air dan saluran primer perkotaan guna menjamin kenyamanan aktivitas warga dan ketahanan ruang kota.</p>',
                'views_count' => 360,
                'is_published' => true,
                'published_at' => now()->subHours(2),
            ],
            [
                'category_id' => $savedNewsCats['RIDA']->id,
                'author_id' => $superAdmin?->id,
                'title' => 'Diseminasi Hasil Riset Kebijakan Daerah Bersama BRIN dan Kolaborasi Perguruan Tinggi',
                'slug' => Str::slug('Diseminasi Hasil Riset Kebijakan Daerah Bersama BRIN dan Kolaborasi Perguruan Tinggi'),
                'excerpt' => 'Bidang RIDA memaparkan 10 rekomendasi riset strategis guna mengakselerasi transformasi pelayanan publik dan ekonomi daerah.',
                'content' => '<p>Kolaborasi riset antara BAPPERIDA Pringsewu dengan BRIN menghasilkan serangkaian rekomendasi berbasis bukti (evidence-based policy). Kebijakan ini diharapkan mampu mendongkrak efektivitas program pembangunan daerah tahun 2026.</p>',
                'views_count' => 520,
                'is_published' => true,
                'published_at' => now()->subMinutes(90),
            ],
        ];

        foreach ($articles as $art) {
            NewsArticle::firstOrCreate(['slug' => $art['slug']], $art);
        }

        // 5. Indeks Pembangunan Daerah Resmi
        $indexes = [
            [
                'name' => 'Indeks Inovasi Daerah (IID)',
                'code' => 'IID',
                'year' => 2025,
                'score' => 62.45,
                'predicate' => 'Sangat Inovatif',
                'evaluator' => 'Badan Strategi Kebijakan Dalam Negeri (BSKDN) Kemendagri RI',
                'description' => 'Penilaian tahunan terhadap kematangan dan dampak ekosistem inovasi pelayanan publik dan tata kelola pemerintah daerah.',
                'is_active' => true,
            ],
            [
                'name' => 'Indeks Daya Saing Daerah (IDSD)',
                'code' => 'IDSD',
                'year' => 2025,
                'score' => 3.42,
                'predicate' => 'Tinggi',
                'evaluator' => 'Badan Riset dan Inovasi Nasional (BRIN)',
                'description' => 'Pengukuran produktivitas dan pilar daya saing daerah yang mencakup lingkungan pendukung, SDM, pasar, dan inovasi.',
                'is_active' => true,
            ],
            [
                'name' => 'Indeks Pengelolaan Keuangan Daerah (IPKD)',
                'code' => 'IPKD',
                'year' => 2025,
                'score' => 84.10,
                'predicate' => 'Baik',
                'evaluator' => 'Kementerian Dalam Negeri RI & BPKP',
                'description' => 'Evaluasi transparansi, akuntabilitas, dan efektivitas alokasi belanja modal serta pendapatan daerah.',
                'is_active' => true,
            ],
            [
                'name' => 'Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP / SAKIP)',
                'code' => 'SAKIP',
                'year' => 2025,
                'score' => 82.30,
                'predicate' => 'Predikat A',
                'evaluator' => 'KemenPAN-RB',
                'description' => 'Penilaian efektivitas penggunaan anggaran berbasis kinerja dan pencapaian target sasaran RPJMD.',
                'is_active' => true,
            ],
        ];

        foreach ($indexes as $idx) {
            RegionalIndex::firstOrCreate(
                ['code' => $idx['code'], 'year' => $idx['year']],
                $idx
            );
        }

        // 6. Pejabat Struktural & Fungsional BAPPERIDA (Perbup No. 38/2025)
        $officials = [
            [
                'name' => 'Dr. IMAM FATKUROJI, S.STP., M.IP',
                'nip' => '19841110 200312 1 001',
                'position' => 'Kepala BAPPERIDA Kabupaten Pringsewu',
                'category_code' => 'leadership',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'SITI RAHMAH, S.I.Kom., MM',
                'nip' => '19850609 201001 2 014',
                'position' => 'Sekretaris BAPPERIDA',
                'category_code' => 'structural',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'FITRI FAULA, S.I.Kom',
                'nip' => '19880429 201001 2 006',
                'position' => 'Kasubbag Umum dan Kepegawaian',
                'category_code' => 'structural',
                'order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'EVY SURYANI SIMATUPANG, MM',
                'nip' => '19830331 201101 2 006',
                'position' => 'JF Perencana Ahli Muda',
                'category_code' => 'functional',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'FEBBY SABEL SUPRIYATNA, SE, MM',
                'nip' => '19860204 201001 2 021',
                'position' => 'JF Analis Keuangan Pusat dan Daerah Ahli Muda',
                'category_code' => 'functional',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'RARA SUKMA, ST., M.P.W.K',
                'nip' => '19850724 201001 2 016',
                'position' => 'Kepala Bidang PPE (Perencanaan, Pengendalian & Evaluasi)',
                'category_code' => 'structural',
                'order' => 6,
                'is_active' => true,
            ],
            [
                'name' => 'Ir. A. ADAM ALTHUSIUS, ST., MURP.',
                'nip' => '19800422 201001 1 009',
                'position' => 'Kepala Bidang IPW (Infrastruktur & Pengembangan Wilayah)',
                'category_code' => 'structural',
                'order' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'DEBIT ZULIANSYAH, ST',
                'nip' => '19801012 201001 1 023',
                'position' => 'Kepala Bidang PPM (Pemerintahan & Pembangunan Manusia)',
                'category_code' => 'structural',
                'order' => 8,
                'is_active' => true,
            ],
            [
                'name' => 'Ir. ERWIN SONI, ST., MM',
                'nip' => '19801208 201001 1 011',
                'position' => 'Kepala Bidang PSDA (Perekonomian & SDA)',
                'category_code' => 'structural',
                'order' => 9,
                'is_active' => true,
            ],
            [
                'name' => 'FENNY APRILIA, S.Sos',
                'nip' => '19840405 201001 2 032',
                'position' => 'Kepala Bidang RIDA (Riset & Inovasi Daerah)',
                'category_code' => 'structural',
                'order' => 10,
                'is_active' => true,
            ],
        ];

        foreach ($officials as $off) {
            Official::updateOrCreate(['nip' => $off['nip']], $off);
        }

        // 7. Prestasi & Penghargaan Daerah (Award Showcase)
        $awards = [
            [
                'name' => 'Penghargaan Pembangunan Daerah (PPD) Terbaik I Tingkat Provinsi Lampung',
                'slug' => Str::slug('Penghargaan Pembangunan Daerah PPD Terbaik I Tingkat Provinsi Lampung'),
                'year' => 2025,
                'award_date' => '2025-04-18',
                'category' => 'Perencanaan Pembangunan',
                'organizer' => 'Kementerian PPN / Bappenas & Pemprov Lampung',
                'description' => 'Apresiasi tertinggi atas keterpaduan, konsistensi, dan inovasi perencanaan pembangunan daerah dalam penyusunan RKPD Kabupaten Pringsewu yang selaras dengan sasaran strategis nasional.',
                'image_path' => '/images/awards/award_ppd_pringsewu.jpg',
                'order' => 1,
                'is_published' => true,
            ],
            [
                'name' => 'Innovative Government Award (IGA) - Predikat Sangat Inovatif',
                'slug' => Str::slug('Innovative Government Award IGA Predikat Sangat Inovatif'),
                'year' => 2025,
                'award_date' => '2025-12-12',
                'category' => 'Inovasi Daerah',
                'organizer' => 'Kementerian Dalam Negeri Republik Indonesia (BSKDN)',
                'description' => 'Penghargaan nasional atas capaian skor kematangan indeks inovasi daerah (IID) 62,45 melalui penerapan puluhan aplikasi layanan publik dan tata kelola pemerintahan desa berbasis digital.',
                'image_path' => '/images/awards/award_iga_pringsewu.jpg',
                'order' => 2,
                'is_published' => true,
            ],
            [
                'name' => 'Akuntabilitas Kinerja Instansi Pemerintah (SAKIP Award) Predikat A',
                'slug' => Str::slug('Akuntabilitas Kinerja Instansi Pemerintah SAKIP Award Predikat A'),
                'year' => 2025,
                'award_date' => '2025-10-06',
                'category' => 'Akuntabilitas Kinerja',
                'organizer' => 'Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi (KemenPAN-RB)',
                'description' => 'Pengakuan atas keberhasilan BAPPERIDA dalam efisiensi penggunaan anggaran berbasis kinerja, konsistensi pohon kinerja indikator makro, dan akuntabilitas tata kelola birokrasi.',
                'image_path' => '/images/awards/award_ppd_pringsewu.jpg',
                'order' => 3,
                'is_published' => true,
            ],
            [
                'name' => 'Penghargaan Kinerja Penurunan Prevalensi Stunting Terbaik',
                'slug' => Str::slug('Penghargaan Kinerja Penurunan Prevalensi Stunting Terbaik'),
                'year' => 2025,
                'award_date' => '2025-08-20',
                'category' => 'Pembangunan Manusia',
                'organizer' => 'BKKBN & Tim Percepatan Penurunan Stunting (TPPS) Pusat',
                'description' => 'Apresiasi komitmen konvergensi lintas sektor intervensi gizi spesifik dan sensitif di 126 pekon dan 5 kelurahan se-Kabupaten Pringsewu menuju zero new stunting.',
                'image_path' => '/images/awards/award_iga_pringsewu.jpg',
                'order' => 4,
                'is_published' => true,
            ],
            [
                'name' => 'Opini Wajar Tanpa Pengecualian (WTP) 9 Kali Berturut-turut',
                'slug' => Str::slug('Opini Wajar Tanpa Pengecualian WTP 9 Kali Berturut turut'),
                'year' => 2024,
                'award_date' => '2024-05-15',
                'category' => 'Pengelolaan Keuangan',
                'organizer' => 'Badan Pemeriksa Keuangan Republik Indonesia (BPK RI)',
                'description' => 'Opini audit tertinggi atas Laporan Keuangan Pemerintah Daerah (LKPD) yang menunjukkan transparansi, kepatuhan regulasi, dan akurasi pencatatan aset daerah.',
                'image_path' => '/images/awards/award_ppd_pringsewu.jpg',
                'order' => 5,
                'is_published' => true,
            ],
            [
                'name' => 'TPID Award - Tim Pengendalian Inflasi Daerah Berprestasi Kawasan Sumatera',
                'slug' => Str::slug('TPID Award Tim Pengendalian Inflasi Daerah Berprestasi Kawasan Sumatera'),
                'year' => 2024,
                'award_date' => '2024-06-14',
                'category' => 'Daya Saing & Perekonomian',
                'organizer' => 'Kementerian Koordinator Bidang Perekonomian & Bank Indonesia',
                'description' => 'Penghargaan atas inovasi penguatan rantai pasok pangan lokal, operasi pasar murah terpadu, dan kestabilan inflasi daerah yang terjaga di batas aman.',
                'image_path' => '/images/awards/award_iga_pringsewu.jpg',
                'order' => 6,
                'is_published' => true,
            ],
            [
                'name' => 'Peringkat I Indeks Daya Saing Daerah (IDSD) Klaster Kabupaten Se-Provinsi Lampung',
                'slug' => Str::slug('Peringkat I Indeks Daya Saing Daerah IDSD Klaster Kabupaten Se Provinsi Lampung'),
                'year' => 2024,
                'award_date' => '2024-11-28',
                'category' => 'Daya Saing & Perekonomian',
                'organizer' => 'Badan Riset dan Inovasi Nasional (BRIN)',
                'description' => 'Capaian pilar produktivitas tenaga kerja, infrastruktur pendukung ekonomi kerakyatan, dan kemudahan berusaha bagi sentra agribisnis dan UMKM Pringsewu.',
                'image_path' => '/images/awards/award_ppd_pringsewu.jpg',
                'order' => 7,
                'is_published' => true,
            ],
            [
                'name' => 'Anugerah Keterbukaan Informasi Publik (KIP) Kategori Informatif',
                'slug' => Str::slug('Anugerah Keterbukaan Informasi Publik KIP Kategori Informatif'),
                'year' => 2023,
                'award_date' => '2023-12-05',
                'category' => 'Tata Kelola Pemerintahan',
                'organizer' => 'Komisi Informasi Provinsi Lampung',
                'description' => 'Penghargaan tertinggi atas kepatuhan standar layanan informasi publik berkala dan keterbukaan akses dokumen perencanaan melalui portal resmi daerah.',
                'image_path' => '/images/awards/award_iga_pringsewu.jpg',
                'order' => 8,
                'is_published' => true,
            ],
        ];

        foreach ($awards as $awd) {
            Award::firstOrCreate(['slug' => $awd['slug']], $awd);
        }
    }
}
